spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      url: jdbc:redis://redis:@127.0.0.1:6379
      connect-timeout: 10
  
  datasource:
    url: jdbc:mysql://database-payment.cde4a8am48qh.ap-northeast-2.rds.amazonaws.com/payment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: qwer1234!


    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active: local
    include: API-KEY

  jwt:
    header: Authorization
    prefix: Bearer
    secret: cGxheWdyb3VuZC1zcHJpbmctYm9vdC10ZWFtcHJvamVjdC1sb2dpbi1qd3Qtc2VjcmV0LWtleQo=
    token-valid-time: 3600000 # 1hour

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      url: jdbc:redis://redis:@127.0.0.1:6379
      connect-timeout: 10
logging:
  level:
    root: INFO
