spring:

  data:
    redis:
      host: redis.o42kc5.ng.0001.apn2.cache.amazonaws.com
      port: 6379
      connect-timeout: 10

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-payment.cde4a8am48qh.ap-northeast-2.rds.amazonaws.com/payment?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: qwer1234!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database: mysql
    defer-datasource-initialization: true

  jwt:
    header: Authorization
    prefix: Bearer
    secret: cGxheWdyb3VuZC1zcHJpbmctYm9vdC10ZWFtcHJvamVjdC1sb2dpbi1qd3Qtc2VjcmV0LWtleQo=
    token-valid-time: 3600000 # 1hour