spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql

    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active: local
    include: API-KEY

  jwt:
    header: Authorization
    prefix: Bearer
    secret: cGxheWdyb3VuZC1zcHJpbmctYm9vdC10ZWFtcHJvamVjdC1sb2dpbi1qd3Qtc2VjcmV0LWtleQo=
    token-valid-time: 3600000 # 1hour

logging:
  level:
    root: INFO